server:
  port: 8081
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: RCC
    password: rcc123
    driverClassName: oracle.jdbc.OracleDriver
  cache:
    type: redis
    redis:
      time-to-live: 60000 # 缓存超时时间ms
      cache-null-values: false # 是否缓存空值
  redis:
    host: localhost
    port: 6379